/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	//1. Enable all configurable exceptions like usage fault, mem manage fault and bus fault.
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR|= (1<<16); //mem manage fault
	*pSHCSR|= (1<<17); //bus fault
	*pSHCSR|= (1<<18); //USAGE Fault



	//3. lets force the processor to execute some undefined instructions
	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xFFFFFFFF;

	void (*some_address) (void);

	some_address = (void*)(((uint32_t)pSRAM)+1);  //for T-bit (last bit needs to be one
	some_address();
	//4 analyze the fault

	for(;;);
}


//2. implement the fault handlers
void MemManage_Handler(void)
{
	printf("Exception: Hard fault\n");
	while(1);
}
void BusFault_Handler(void)
{
	printf("Exception: Bus fault\n");
	while(1);
}

__attribute__ ((naked)) void UsageFault_Handler(void)//caller
{
	//here we extracted the value of MSP which happens to be the
	//base address of the stack frame(thread mode) which got saved during the exception entry
	//from thread mode to handler mode
	__asm ("MRS r0,MSP"); //this is a naked function only assembly code, so that no prologue or epilogue code
	__asm ("B UsageFault_Handler_c");

}
void UsageFault_Handler_c(uint32_t *pBaseStackFrame)//callee
{
	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("Exception: Usage fault\n");
	printf("UFSR = %lx\n",(*pUFSR) & 0xFFFF);
	printf("pBaseStackFrame = %p\n",pBaseStackFrame);
	printf("Value of R0 = %lx\n", pBaseStackFrame[0]);
	printf("Value of R1 = %lx\n", pBaseStackFrame[1]);
	printf("Value of R2 = %lx\n", pBaseStackFrame[2]);
	printf("Value of R3 = %lx\n", pBaseStackFrame[3]);
	printf("Value of R12 = %lx\n", pBaseStackFrame[4]);
	printf("Value of LR = %lx\n", pBaseStackFrame[5]);
	printf("Value of PC = %lx\n", pBaseStackFrame[6]);
	printf("Value of XPSR = %lx\n", pBaseStackFrame[7]);
	while(1);
}

void HardFault_Handler (void)
{
	printf("Exception: Hard fault\n");
	while(1);
}
