/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/* This function executes in THREAD MODE of the processor */
void generate_interrupt()
{
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//enable IRQ3 interrupt
	*pISER0 |= ( 1 << 3);

	//generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);

}

void change_access_level_unpriv(void)
{
	//Read
	__asm volatile("MRS R0,CONTROL");
	//Modify
	__asm volatile("ORR R0, R0,#0x01");
	//Write
	__asm volatile("MSR CONTROL,R0");
}
/* This function executes in THREAD MODE+privileged access level of the processor */
int main(void)
{
	printf("In thread mode : before interrupt\n");

	void (*fun_ptr)(void);
	fun_ptr = (void*)0x80001c8;

	fun_ptr(); //use () ; to deference the function pointer and jump to the function
	//the address of change_access_level_unpriv address is loaded into the Program counter (To see the T-bit)
	printf("In thread mode : after interrupt\n");

	for(;;);
}

/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode : ISR\n");
}

void HardFault_Handler()
{
	printf("Hard Fault Detected\n");
	while(1);
}

